### ISSUE TITLE
Add support for Logsene-only token for CoreOS

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-docker#10]
There is support for SPM-only token already, so we need to do the same for Logsene-only.

**Comment by megastef** [comment]
Script is here: 
https://github.com/sematext/sematext-agent-docker/blob/master/coreos/install_logsene_service.sh

SPM could be added later by setting:
`etcdctl set /sematext.com/myapp/spm/token YOUR_SPM_DOCKER_TOKEN`
and restart of `spm-agent-docker.service` via `fleetctl`.
