### ISSUE TITLE
Docker Cloud + Logsene does not handle multi-line logs, nor does it parse the level correctly

### ISSUE THREAD

**Issue by tmbell** [sematext/sematext-agent-docker#11]
I am trying to configure Logsene to handle multiline logs / stack dumps, but I can’t figure out where to start.  We are using docker cloud, and configured Logsene according to this blog-post: https://sematext.com/blog/2016/04/04/docker-cloud-monitoring-logging/

I am at a loss as to where I would find the files described in this blog post: https://sematext.com/blog/2015/05/26/handling-stack-traces-with-logstash

I have attached a file with several examples of a stack-dumps one log per line:

[export.csv.zip](https://github.com/sematext/sematext-agent-docker/files/284668/export.csv.zip)

**Comment by megastef** [comment]
Hi, it would be better to have a text file (e.g. docker -f logs badContainer > test.log - just in case line breaks would not be correctly encoded... I've extracted the message field and wrote it to a new file. When I pass it to [logagent](http://sematext.github.io/logagent-js/), stack traces seems to be OK. 
`cat ../../test-log.txt | logagent  -y`

See screenshot. 
![bildschirmfoto 2016-05-26 um 18 24 20](https://cloud.githubusercontent.com/assets/7289505/15582002/213f6d1c-236f-11e6-8908-43fc1e97c235.png)

I could imagine, that this a timing problem, the multi-line parser waits max 300ms for the next line/defined regular expression for the block start. If Java is writing stack traces slowly, lines could be recognized as separate line. We could make multi-line parser parameters configurable on Docker Cloud to see if a higher timeout would help.

**Comment by megastef** [comment]
Please note Sematext Docker Agent uses [logagent](http://sematext.github.io/logagent-js/), and not Logstash to parse logs.

**Comment by megastef** [comment]
Please add to the environment section in the Docker Cloud stack file the setting for 2 second timeout (300ms is the default): 

```
- LOGAGENT_MULTILINE_TIMEOUT_MS=2000
```

And use the new image: `sematext/sematext-docker-agent:dev` for a test. Image build is complete: https://hub.docker.com/r/sematext/sematext-agent-docker/builds/
If it turns out that this is the reason, we could adjust defaults in the regular image.

**Comment by otisg** [comment]
@tmbell does this work for you?  Would be great if you could confirm.  Thanks!

**Comment by tmbell** [comment]
I handed the issue off to kanderson **at** selkirksystems **dot** com  She has not been successful as of yet.  I believe you have been emailing her

**Comment by otisg** [comment]
Thanks @tmbell . Looks like kanderson got it working, so closing this.
