### ISSUE TITLE
Problem with Kubernetes and Rancher

### ISSUE THREAD

**Issue by marlinhares** [sematext/sematext-agent-docker#17]
For this work on my environment I had to use 
**hostNetwork: true**
inside spec of the daemon set

My environment:
Azure
CoreOs 1185.2
Rancher 1.1.4
Kubernetes

**Comment by megastef** [comment]
The agent must have internet access to https access to sematext.com (if you use SaaS, default). Or it must be able to reach the On-Prem SPM/Logsene servers.

**Comment by megastef** [comment]
@marlinhares could you provide a PR for https://github.com/sematext/sematext-agent-docker/blob/master/kubernetes/sematext-agent.yml ?

**Comment by marlinhares** [comment]
Done @megastef

**Comment by megastef** [comment]
Tested. Thanks @marlinhares for the PR https://github.com/sematext/sematext-agent-docker/pull/19
