### ISSUE TITLE
Filtering data and multi line data

### ISSUE THREAD

**Issue by random0000** [sematext/sematext-agent-docker#24]
Is it possible to filter/edit data in the docker agent before it is sent out to Sematext?  Also, is there a way to handle multi line logs (i.e. a stack trace)? Is there a better place to ask questions such as these?

Thanks!

**Comment by otisg** [comment]
Hi @random0000 

https://groups.google.com/forum/#!forum/sematext-docker-agent is the mailing list you can use for questions.

Multi-line logs are supported.  If that is not working for you best to open a ticket here, share your config and a sample of your logs.

Filtering is doable, too.  Maybe best to ask on the mailing list what you want to filter and how?

**Comment by megastef** [comment]
Configuration for SDA:
https://sematext.com/docker-datacenter-monitoring-and-logging/configuring-sematext-docker-agent/

**Comment by megastef** [comment]
Closing. Feel free to contact us for additional support (like pattern definition or agent config).
