### ISSUE TITLE
Add support / docs for using Docker Secrets

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-docker#25]
Or maybe this is already doable?

**Comment by otisg** [comment]
It looks like this can be done now, so closing.

**Comment by megastef** [comment]
A short documentation is in the README. Search for "secrets".  The path/filename for docker secrets could be changed e.g. via ```-e CONFIG_FILE=/run/secrets/my-sda-secret-config```.  
An alternative is to use the docker service create command to change the name of the secret file in the container e.g. 
```
docker service create --secret source=my-sda-secret-config,target=sematext-agent  ...
```
 to match the default file name `/run/secrets/sematext-agent`. I'll add the docker command to the documentation.
