### ISSUE TITLE
Add new field service_name for docker swarm

### ISSUE THREAD

**Issue by pickfire** [sematext/sematext-agent-docker#27]
Hi, I had used sematext with docker swarm setup and I found out that sematext-agent-docker doesn't provide `service_name` to sematext. I think it would be nice to add that field.

The current workaround for this is to filter based on `container_name: "container.*"`.

**Comment by otisg** [comment]
I think this makes sense.  Would you be able to do a PR by any chance?

**Comment by pickfire** [comment]
@otisg I don't quite understand the stuff under the hood so probably not.

**Comment by megastef** [comment]
@pickfire We are working on it, I hope we can share a solution tomorrow. You would find service name in SPM image/pod filter and logs will be tagged with Swarm labels. BTW, you could extract the swarm labels for logs using the e.g. `-e TAGGING_LABELS='com.docker.swarm*,com.myapp.*'` option in SDA, see https://github.com/sematext/sematext-agent-docker#configuration-parameters.

**Comment by pickfire** [comment]
@megastef I have added that. But I don't see any difference.

**Comment by megastef** [comment]
@pickfire Do you mean in SPM? Please try sematext/sematext-agent-docker:1.31.26  you will find service name in the image filter and logs get swarm label fields `swarm_service_name`, `swarm_task_id` `swarm_node_id`  attached (no need for TAGGING_LABELS)
