### ISSUE TITLE
Add more info to diagnostics file

### ISSUE THREAD

**Issue by megastef** [sematext/sematext-agent-docker#29]
- [x] - Docker Engine Version / Docker Info output
- [x] - Collect a few seconds metrics to check docker api original values
- [x] - Check network connectivity to Sematext Cloud or On-Prem receivers

**Comment by otisg** [comment]
Should we capture other version numbers in addition to Docker Engine version?

**Comment by megastef** [comment]
We capture Docker version (only when connection to Docker works), Node.js version, OS version ...
- [x] - Docker Engine Version / Docker Info output
- [x] - Collect a few seconds metrics to check docker api original values
- [x] - Check network connectivity to Sematext Cloud
