### ISSUE TITLE
Collect Kubernetes-specific metrics

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-docker#31]
After detecting k8s via #30.

**Comment by megastef** [comment]
SDA collects already container & host stats and k8s logs (tagged with k8s metadata). The UI has filters per pod (and metrics are aggregated per pod). 

I assume we could add
- tracking k8s events / POD deployment status
- number of pods for each state
- number of nodes in the cluster

**Comment by otisg** [comment]
But that should be handled by STA now, right?

**Comment by megastef** [comment]
Right
