### ISSUE TITLE
logparser regex for Nginx is incorrect

### ISSUE THREAD

**Issue by sn0opy** [sematext/sematext-agent-docker#33]
The default regex for Nginx access logs doesn't seem to be correct. 

The regex ends after the user agent, even though the default nginx.conf includes `"$http_x_forwarded_for"` right after that. At least on Ubuntu and the nginx alpine docker image.

Default Log format:

```
log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "$http_x_forwarded_for"';
```

Most of the time, this will just appear as a `"-"` in the log files. 

The support told me, that the whole log line has to match to get properly parsed.

**Comment by otisg** [comment]
@sn0opy You could simply create an additional regular expression for your particular Nginx format.  You could copy the existing expression for Nginx and modify it to work with your format.
Do you know where/how to do that?

**Comment by megastef** [comment]
Which image do you use exactly? 

We could add an additional pattern for nginx to match more fields. This pattern should be the first one for nginx, to avoid that the parser uses the simplest rule. In general the most complex rules should be listed first.

BTW, it is possible to use custom patterns in Sematext Docker Agent (SDA), by passing your patterns.yml  to SDA via mounted volume, environment variable or URL. See https://sematext.com/docker-enterprise-monitoring-and-logging/configuring-sematext-docker-agent/

@sn0opy, if you got the pattern working (support e-mails), could you  please make a pull request?

**Comment by sn0opy** [comment]
Basically, you can ignore this issue. From my first unterstanding (after talking to the support), the whole regex had to match, to get the log message parsed. Now I know that the sourceName needs to match. After that, the regex will be used to map the information to the correct fields. 

In this case, the log will be parsed properly. Only the information from `$http_x_forwarded_for` will be left out, which is not necessary anyway.

@otisg @megastef I know about the possibility to use a different pattern.yml, yes. My initial idea was, to make you aware about the actual default log format for nginx.

@megastef I'm the nginx-alpine image. you can find the default nginx.conf in this repo  https://github.com/nginxinc/docker-nginx

**Comment by megastef** [comment]
@sn0opy thanks a lot! We will add a pattern for nginx-alpine
