### ISSUE TITLE
Make it possible to ship data to an on-premises version of SPM/Logsene

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-docker#4]
i.e. one should be able to change the Receiver URL.  Or maybe we just need to document where/how to do that.

**Comment by megastef** [comment]
+1 In the next release. This is possible today:

```
-e spmagent_spmSenderBulkInsertUrl=https://spm-receiver.sematext.com:443/receiver/v1/_bulk
-e LOGSENE_URL=https://logsene-receiver.sematext.com/_bulk
```

But the start script could map another variable like SPM_URL to spmagent_spmSenderBulkInsertUrl.

**Comment by otisg** [comment]
Sounds good

**Comment by megastef** [comment]
Changes done and Readme updated to use SPM_URL and LOGSENE_URL for on-premises servers.
