### ISSUE TITLE
Remove Node 0.12 from Travis

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-docker#40]
It's causing the build to fail

**Comment by megastef** [comment]
Failed Travis test is not related to the Node version. The check for indexed log count fails (perhaps indexing takes longer than usual).

**Comment by megastef** [comment]
Fixed. Using a different version of gc-stats.

**Comment by megastef** [comment]
Fixed, changed Elasticsearch query to check log count (nginx output changed).
