### ISSUE TITLE
add df statistic

### ISSUE THREAD

**Issue by gregwebs** [sematext/sematext-agent-docker#5]
https://www.npmjs.com/package/node-diskfree

I would like to get a warning when my host is running out of disk space

**Comment by megastef** [comment]
You should get the warning already.  
1) The metrics are already collected: https://github.com/sematext/sematext-agent-docker/blob/master/lib/linuxAgent.js#L43
And SPM generates default alerts for 95% disk usage.  Navigate to App-Settings / Alerts / Alert Rules - here you could change the value of the rule "Automatic alert - disk usage > 95%" to a lower value like 80%. 

2) There is a problem in the UI, the disk space reports are missing in the current version, this will be fixed  soon (next UI update) - then you can create alerts for disk space using the UI. 
To define an alert you could use the SPM API: http://blog.sematext.com/2015/04/01/spm-rest-api/
Here is an example, you might need to change estimatedValue (% disk usage), sendToEmail, apiKey and appToken:

```
curl -X POST -k -H "Content-Type: application/json" "https://apps.sematext.com/spm-reports/api/v2/alert/threshold/add" -d '{

  "alertRule": {
    "name": "Disk Space Used Alert",
    "enabled": "true",
    "estimateOperation": "MORE",
    "analyzingTime": "05",
    "backToNormalNeeded": false,
    "ignoreRegularEventsEnabled": true,
    "muteTimePeriodInMinutes": "30",
    "minDelayBetweenNotificationsInMinutes": "1",
    "maxNotificationsInMutePeriod": "3",
    "filterValues": "http:/host?hostFilter_selected=any&diskFilter_selected=any&&timeIntervalFilter_dataRetentionHours=4320&numfilcom=1",
    "metricLabel": "used space",
    "estimateValue": 80,
    "reportName": "diskReportPage",
    "chartKey": "ds",
    "sendToEmail": "stefan.thies@sematext.com"
  },
  "apiKey": "XXXXXXXX-XXXX-XXXXXXXXXXXX",
  "appToken": "XXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXX"

}'
```

**Comment by gregwebs** [comment]
oh, great! Please close this when the UI is updated.

**Comment by megastef** [comment]
The UI update was deployed this morning to https://apps.sematext.com - including Disk I/O stats and Disk Space report in the OS tab. 

![](https://sematext.files.wordpress.com/2016/02/host-disk-space1.png)

In the chart Action Menu, you can find the alert definition as usual...
![](https://sematext.files.wordpress.com/2016/02/disk-space-alert-definition.png)
