### ISSUE TITLE
Provide a tag for the Alpine Linux build on Docker Hub

### ISSUE THREAD

**Issue by blueimp** [sematext/sematext-agent-docker#6]
You still provide an alternative Dockerfile for an image based on Alpine Linux.

However the `Dockerfile.alpine` doesn't have a related tag on Docker Hub, meaning that users have to build and maintain the image themselves.

Could you therefore set up an additional automated build on Docker hub with an alternative tag, e.g. `sematext/sematext-agent-docker:alpine-1.29.30`?

Thanks for your consideration!

**Comment by megastef** [comment]
I hope we can switch back to alpine, when the bugs get fixed: http://bugs.alpinelinux.org/issues/5130#change-14946

**Comment by blueimp** [comment]
I understand that you cannot use Alpine as default image until that bug is fixed, however this does not seem to affect all host systems.

What I was asking was if you could provide an alternative tag for the alpine based image for folks who don't run CoreOS as host?

**Comment by megastef** [comment]
It looks the problem of Alpine + CoreOS could be solved by installing "coreutils". 
See https://github.com/docker-library/official-images/issues/1449#issuecomment-191475924
I made the required changes, including Alpline image as default in 1.29.32  with 94 MB size. After the tests 1.29.32 will get the "latest" tag.

**Comment by megastef** [comment]
Docker Agent with Alpine Linux works with "coreutils" installed (v1.29.32), reporting correct disk space on 
- CoreOS 983.0.0
- CoreOS 991.0.0

`sematext/sematext-agent-docker:latest` switched to Alpine Linux again and we will continue to use Alpine base image. 
Thanks @blueimp for contributing here!

![docker-build-latest](https://cloud.githubusercontent.com/assets/7289505/13914385/5663ede2-ef4e-11e5-87c3-9282847f2a4b.png)
.
