### ISSUE TITLE
Support multiple Logsene tokens

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-docker#9]
This is from https://github.com/sematext/spm-agent-docker/issues/5
If I have 2 containers, one running Apache and the other one running Elasticsearch, just for example, I may actually want to send their logs to 2 different Logsene apps.

**Comment by megastef** [comment]
We could use the Docker API to scan conainer labels of started container for LOGSENE_TOKEN. Users simple add `--label LOGSENE_TOKEN=your_logsene_token` to the Containers run command (Nginx, Elasticsearch, ...) and Sematext Docker Agent will recognize that the Logs should be routed to the specified Logsene Applications. This could be extended to additional config settings like filters (e.g. to log only errors).
Example:

```
  docker run --label LOGSENE_TOKEN=YOUR_ES_APP_TOKEN      
  --label LOGSENE_FILTER="error|exception|warning" -p 9200:9200 elasticsearch
  docker run -e LOGSENE_TOKEN=YOUR_WEB_APP_TOKEN -p 80:80 nginx
```

Logs of containers without LOGSENE_TOKEN will be routed to the default Logsene App specified during startup of sematext/sematext-agent-docker.

**Comment by megastef** [comment]
There is an interesting discussion to update labels at runtime: https://github.com/docker/docker/pull/18958
Once label updates are available we could change routing to apps dynamically by changing the labels.

**Comment by megastef** [comment]
Done in Github master and published on Docker Hub sematext/sematext-agent-docker:dev and sematext/sematext-agent-docker:1.29.33 (build running)
After successful tests it can be published on Docker Hub with the latest tag. 
Documentation: https://github.com/sematext/sematext-agent-docker#log-routing  
This does not include LOGSENE_FILTERS (separate feature ...).

**Comment by szakasz** [comment]
Fantastic, thanks for the quick enhancement. I also find this solution very good.

**Comment by megastef** [comment]
Thx @szakasz if you like to test, pls. let me know if you see any issue. I will run the new agent on our test server too ...

**Comment by otisg** [comment]
Awesome :)

**Comment by szakasz** [comment]
Hi @megastef, I've tried to do some testing. Unfortunately, it turns out that Kubernetes and hence OpenShift 3 doesn't support labelling of the Docker containers directly (https://github.com/kubernetes/kubernetes/issues/3764). Labels are available and customizable at higher levels like pods or Services, but custom labels don't get propagated to the Docker container.

Therefore in this form we cannot test and use this new feature. Would it maybe be possible to add a similar option for Docker environment variables the same way as described in https://github.com/sematext/spm-agent-docker/issues/5#issuecomment-143657965? You could maybe first check the env var LOGSENE_TOKEN, if that's not set then the label LOGSENE_TOKEN, and finally if neither is set then use the default one specified at the Startup of SPM. What do you think?

**Comment by megastef** [comment]
Interesting :) - sure we can check env vars too. Give me a second ... ;) This shows the first idea is always the best one. As far I know Kubernetes is planning to use docker labels in the future (as soon labels can be updated ...). 
Do you know how to query pod labels by container id with Kubernetes API? 
Just curious as we are working on improvements for Kuberntes too.

**Comment by szakasz** [comment]
Thanks for the quick reply. Unfortunately I am not such an expert with Kubernetes, but it would be definitely a very good solution, if you could grab the labels of the pod where the container sits in. I am sure this is documented somewhere.

**Comment by megastef** [comment]
Ok, anyhow I'm working on the environment variables. Takes a bit, as those are arrays to search instead of simple dictionaries like the labels.

**Comment by megastef** [comment]
Build done for sematext/sematext-agent-docker:1.29.35 and sematext/sematext-agent-docker:dev
https://hub.docker.com/r/sematext/sematext-agent-docker/builds/

```
docker run --label LOGSENE_TOKEN=REPLACE_WITH_YOUR_LOGSENE_TOKEN -p 80:80 nginx
# or use environment variable on Kubernetes (no support for Docker labels)
docker run -e LOGSENE_TOKEN=REPLACE_WITH_YOUR_LOGSENE_TOKEN -p 80:80 nginx
```

When this runs fine for a while on the test servers, we will tag it with "latest". 
On each log event a cache is checked, and if there is no entry docker inspect is triggered with label and env var search to make sure that logs don't go to the default LOGSENE_TOKEN. 
The info from "docker inspect" is cached to avoid too many Docker API calls and the cache gets cleared by Docker Events. On "start" and "attach" events the check for LOGSENE_TOKEN is cached (in the hope that the token is available for the first log line arrives), on "die" event the cache entry gets removed. We have to watch if this has performance impacts for scenarios where containers live very short (start/stop) as it triggers then docker inspect calls. Tests went well so far.

**Comment by megastef** [comment]
sematext/sematext-docker-agent:1.29.36  is :latest on Docker Hub. 
So this feature is available for all users.

**Comment by szakasz** [comment]
Thanks, the first tests have been successful. One minor question though regarding https://github.com/sematext/sematext-agent-docker#log-routing:
What is the order of precedence when checking docker label resp. env-var LOGSENE_TOKEN? If both are defined, which is applied?

**Comment by megastef** [comment]
When both are defined the Label. Highest to lowest priority:
1. Container Label
2. if no Label is set, env var for app Container
3. else global Logsene token set for the sematext agent as env variable
